# Generated by Django 2.2.6 on 2019-12-18 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='cases',
            field=models.ManyToManyField(to='main_app.Case'),
        ),
    ]
